"#version 330 core\n"
"in vec4 v_col;\n"
"in vec2 v_uv;\n"
"in float v_tex_index;\n"
"layout (location = 0) out vec4 f_color;"
"uniform sampler2D u_tex[8];\n"
"void main() {"
"switch (int(v_tex_index)) {\n"
"case 0: f_color = v_col * texture(u_tex[0], v_uv); break;\n"
"case 1: f_color = v_col * texture(u_tex[1], v_uv); break;\n"
"case 2: f_color = v_col * texture(u_tex[2], v_uv); break;\n"
"case 3: f_color = v_col * texture(u_tex[3], v_uv); break;\n"
"case 4: f_color = v_col * texture(u_tex[4], v_uv); break;\n"
"case 5: f_color = v_col * texture(u_tex[5], v_uv); break;\n"
"case 6: f_color = v_col * texture(u_tex[6], v_uv); break;\n"
"case 7: f_color = v_col * texture(u_tex[7], v_uv); break;\n"
"default: discard;"
"}"
"}";

