"#version 330 core\n"
"layout (location = 0) in vec2 a_pos;\n"
"layout (location = 1) in vec4 a_col;\n"
"layout (location = 2) in vec2 a_uv;\n"
"layout (location = 3) in float a_tex_index;\n"
"out vec4 v_col;\n"
"out vec2 v_uv;\n"
"out float v_tex_index;\n"
"uniform mat4 u_proj;\n"
"void main() {\n"
"  gl_Position = u_proj * vec4(a_pos, 0.f, 1.f);\n"
"  v_col = a_col;\n"
"  v_uv = a_uv;\n"
"  v_tex_index = a_tex_index;\n"
"}\0";
